"""
JARVIS v4 - Coding Tools

Project scaffolding, code generation, explanation, debugging, VS Code launching
and sandboxed execution -- all delegated to the existing CodingAgent.

run_code is the sharp edge. Section 15 forbids executing untrusted code with
unrestricted privileges, and the runner in CodingAgent is a guard rail (isolated
temp cwd, `python -I`, credential-stripped environment, hard timeout) rather than
a real jail: the snippet still runs as this user. So it is registered DANGEROUS
and always asks first. Nothing generated by a model reaches the interpreter
without an explicit "haan", and there is no path that hands a shell command
straight through -- only Python, only through the sandbox helper.
"""

from __future__ import annotations

from typing import List

from security.permissions import PermissionLevel as P
from tools.base import ToolParam, ToolSpec

CATEGORY = "coding"

_LANGUAGE = ToolParam(
    "language", "string", default="python",
    description="Programming language (python, java, cpp, html, javascript, react, c#...).",
)
_CODE = ToolParam("code", "string", required=True, description="Source code to work on.")


CODING_TOOLS: List[ToolSpec] = [
    ToolSpec(
        name="create_project",
        description="Create a project folder with generated starter code and open it in VS Code.",
        permission=P.LOW_RISK,
        category=CATEGORY,
        agent="coding_agent",
        action="create_vscode_project",
        parameters=(
            ToolParam("folder_name", "string", default="JARVIS_Project", description="Project folder name."),
            _LANGUAGE,
            ToolParam("prompt", "string", default="", description="What the project should do."),
            ToolParam("target_dir", "string", default="", description="Where to create it (default: Desktop)."),
        ),
        aliases={
            "name": "folder_name", "project": "folder_name", "project_name": "folder_name",
            "folder": "folder_name", "folder_path": "target_dir", "path": "target_dir",
            "dir": "target_dir", "user_prompt": "prompt", "description": "prompt",
            "lang": "language",
        },
        confirm_template="Sir, '{folder_name}' project banaun {language} me? Haan ya na bataiye.",
        legacy_actions=("create_vscode_project", "new_project", "scaffold_project", "make_project"),
    ),
    ToolSpec(
        name="write_code",
        description="Generate code for a described task and open it in Notepad.",
        permission=P.LOW_RISK,
        category=CATEGORY,
        agent="coding_agent",
        action="generate_code",
        parameters=(
            ToolParam("prompt", "string", required=True, description="What the code should do."),
            _LANGUAGE,
        ),
        aliases={
            "user_prompt": "prompt", "task": "prompt", "description": "prompt",
            "query": "prompt", "user_input": "prompt", "lang": "language",
        },
        confirm_template="Sir, {language} code likh doon? Haan ya na bataiye.",
        legacy_actions=("generate_code", "code", "write_program"),
    ),
    ToolSpec(
        name="explain_code",
        description="Explain what a piece of code does, step by step.",
        permission=P.SAFE,
        category=CATEGORY,
        agent="coding_agent",
        action="explain_code",
        parameters=(_CODE,),
        aliases={"source": "code", "snippet": "code", "text": "code"},
        legacy_actions=("describe_code", "understand_code"),
    ),
    ToolSpec(
        name="debug_code",
        description="Diagnose a code error and produce corrected code.",
        permission=P.SAFE,
        category=CATEGORY,
        agent="coding_agent",
        action="debug_code",
        parameters=(
            _CODE,
            ToolParam("error", "string", default="", description="Error message or stack trace."),
        ),
        aliases={
            "source": "code", "snippet": "code",
            "error_message": "error", "traceback": "error", "stack_trace": "error", "exception": "error",
        },
        legacy_actions=("fix_code", "fix_error", "debug"),
    ),
    ToolSpec(
        name="run_code",
        description=(
            "Run a Python snippet in an isolated temporary directory with a "
            "timeout. Always asks first, and refuses any other language."
        ),
        permission=P.DANGEROUS,
        category=CATEGORY,
        agent="coding_agent",
        action="run_python_sandbox",
        parameters=(
            _CODE,
            ToolParam("language", "string", default="python", description="Only 'python' is supported."),
            ToolParam("timeout", "integer", default=10, description="Kill the code after this many seconds."),
        ),
        aliases={"source": "code", "snippet": "code", "script": "code", "lang": "language", "seconds": "timeout"},
        confirm_template=(
            "Sir, ye code aapke laptop par run karna hai? Ye aapke hi permissions "
            "ke saath chalega. Haan ya na bataiye."
        ),
        legacy_actions=("run_python_sandbox", "execute_code", "run_python", "run_script"),
    ),
    ToolSpec(
        name="open_vscode",
        description="Open a folder (and optionally a file) in VS Code.",
        permission=P.SAFE,
        category=CATEGORY,
        agent="coding_agent",
        action="open_vscode",
        parameters=(
            ToolParam("folder_path", "string", default="", description="Folder to open (default: Desktop)."),
            ToolParam("file_path", "string", default="", description="File to open inside it."),
        ),
        aliases={
            "path": "folder_path", "folder": "folder_path", "dir": "folder_path",
            "project": "folder_path", "file": "file_path",
        },
        legacy_actions=("open_in_vscode", "launch_vscode", "open_editor", "vscode"),
    ),
]

__all__ = ["CODING_TOOLS"]
